### ISSUE TITLE
Explain what a signaling proposal is

### ISSUE THREAD

**Issue by sachayves** [1Hive/honey-pot#300]
![](https://storage.googleapis.com/ethereum-hackmd/upload_b527d0cd32e1dd76b54070b77f5f6404.png)

**Problem**
We shouldn't necessarily assume folks know what a signaling proposal is. 

**Suggestion**
Add a brief explanation above `TITLE`.

**Comment by willjgriff** [comment]
I think we can just update the bottom info box.

@rperez89 Update the warning box message to:

This action will create a signaling proposal which can be voted on by HNY holders but requests no funds. It is used to gather community sentiment for future funding proposals or particular ideas. In order to create a proposal you must first create a post on the 1Hive Forum under the 🌿Proposals category and paste the link to the corresponding post in the LINK field.
