### ISSUE TITLE
Create general error screen

### ISSUE THREAD

**Issue by rperez89** [1Hive/honey-pot#81]
Currently we are not handling network connection errors and we just keep showing the loading ring forever . We need a global error screen . 

<img width="1670" alt="Screen Shot 2020-09-20 at 9 04 01 PM" src="https://user-images.githubusercontent.com/11763623/93726901-d672d880-fb8e-11ea-9368-737b159d147c.png">

cc @fioreb

**Comment by fioreb** [comment]
Here's the link for the design:
https://www.figma.com/file/P06HTzSyb9hExJVpwaUPmA/Honey-Pot-2.0?node-id=838%3A3600

Related to the types of errors, can we have different messages for the different types of error connections? 
I think it would be better to avoid user frustration, a message not too technical but to give him a clear idea of what's happening. I just ask because I read that image but I'm not sure of the different types of error 😅

**Comment by rperez89** [comment]
I think that here is clear that we had a network issue with your design, i think that the other that we need is the app crash screen like we have on the cour right @fabriziovigevani ?

**Comment by fabriziovigevani** [comment]
Yeah, we should also have the app crash error screen as well. 

I think in the particular network error the texts look good but not sure if we should have the `Try again` link, because most likely we are always refetching for the resources so we are already retrying the connection. 

What do you think @rperez89

**Comment by rperez89** [comment]
yes i think that we might not needed because of our retry pattern

**Comment by rperez89** [comment]
And @fioreb for the general crash when the app enters in some state that is unrecoverable in the court we did this 
![Screen Shot 2020-09-25 at 6 08 22 PM](https://user-images.githubusercontent.com/11763623/94316423-b0688200-ff5a-11ea-824d-1493aa91aaef.png)

Showing as an example we might not need any send report because we don't have that service but me might have un `Go to discord` or something

**Comment by fioreb** [comment]
@rperez89  @fabriziovigevani  

https://www.figma.com/file/P06HTzSyb9hExJVpwaUPmA/Honey-Pot-2.0?node-id=903%3A10788

There's the design for the global error. 
To where the "tell us what went wrong" link takes the user? if that takes the user to a chat, we can link Discord there or I can add te Go to Discord button as you suggest Ro!

**Comment by onbjerg** [comment]
Is this coming in v2?
